apiVersion: cloudfunctions.cnrm.cloud.google.com/v1beta1
kind: CloudFunctionsFunction
metadata:
  name: picture-uploaded
spec:
  projectRef:
    external: "projects/asm-workshop-498"
  region: "europe-west2"
  runtime: "nodejs10"
  sourceRepository:
    url: https://source.developers.google.com/projects/asm-workshop-498/repos/serverless-photosharing-workshop/moveable-aliases/main/paths/functions/image-analysis/nodejs/
  entryPoint: "vision_analysis"
  eventTrigger:
    eventType: "providers/cloud.storage/eventTypes/object.change"
    resourceRef:
      name: "uploaded-pictures-asm-workshop-498"
      kind: "StorageBucket"
    service: "storage.googleapis.com"